<?php

namespace AppBundle\Repository;

/**
 * ChiefOrPartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiefOrPartnerRepository extends \Doctrine\ORM\EntityRepository
{
}
