<?php

namespace AppBundle\Repository;

/**
 * ClubForTournamentTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubForTournamentTableRepository extends \Doctrine\ORM\EntityRepository
{
}
