<?php

namespace AppBundle\Repository;

/**
 * FootHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FootHallRepository extends \Doctrine\ORM\EntityRepository
{
}
