<?php

namespace AppBundle\Repository;

/**
 * ForFansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForFansRepository extends \Doctrine\ORM\EntityRepository
{
}
