<?php

namespace AppBundle\Repository;

/**
 * FutureMatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FutureMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
