<?php

namespace AppBundle\Repository;

/**
 * GalleryImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryImageRepository extends \Doctrine\ORM\EntityRepository
{
}
