<?php

namespace AppBundle\Repository;

/**
 * GroupTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
