<?php

namespace AppBundle\Repository;

/**
 * OnlineMatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlineMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
