<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPlayers(int $teamId, int $positionId = null)
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.team', 't')
            ->join('p.position', 'pos')
            ->where('t.id = :teamId')
            ->setParameter('teamId', $teamId);

        if (!empty($positionId)) {
            $query->andWhere('pos.id = :positionId')
                ->setParameter('positionId', $positionId);
        }

        return $query->getQuery()->getResult();
    }
}
