<?php

namespace AppBundle\Repository;

/**
 * PositionPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
