<?php

namespace AppBundle\Repository;

/**
 * TournamentTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentTableRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByActiveAndSort(int $id, \DateTime $firstDate, \DateTime $secondDate)
    {
        return $this->createQueryBuilder('i')
            ->where('i.participant = :id')
            ->setParameter('id', $id)
            ->andWhere('i.createdAt BETWEEN :firstDate AND :secondDate')
            ->andWhere('i.isWinner != 1 or i.isWinner is null')
            ->setParameter('firstDate', $firstDate->format('Y-m-d'))
            ->setParameter('secondDate', $secondDate->format('Y-m-d'))
            ->getQuery();
    }
}
