<?php

namespace AppBundle\Repository;

/**
 * TypeCoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCoachRepository extends \Doctrine\ORM\EntityRepository
{
}
