imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/config.yml }
#    - { resource: doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    app_locales: [ru, kg, en]

framework:
    translator: { fallbacks: ['%locale%'] }
    templating:
        engines: ['twig']

    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        locales: '%app_locales%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_translation:
    locale_switcher: true
    locales: [ru, kg, en]
    default_locale: '%locale%'
    gedmo:
        enabled: true

vich_uploader:
    db_driver: orm
    mappings:
        image_file:
            uri_prefix:         /uploads
            upload_destination: %kernel.root_dir%/../web/uploads
            namer:              vich_uploader.namer_uniqid

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        logo_file:
            uri_prefix:         /uploads/logo
            upload_destination: %kernel.root_dir%/../web/uploads/logo
            namer:              vich_uploader.namer_uniqid

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        flag_file:
                    uri_prefix:         /flags
                    upload_destination: %kernel.root_dir%/../web/flags
                    namer:              vich_uploader.namer_uniqid

                    inject_on_load: false
                    delete_on_update: true
                    delete_on_remove: true

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [330, 240], mode: inset, allow_upscale: false }
        gallery:
            filters:
                downscale:
                    max: [1280, 768]

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            sluggable : true
            timestampable: true
            blameable: true
            translatable: true

lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/app/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/app/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'ffkr' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600



